version: "3"

services: 
  api:
    build: ./api
    ports: 
    - "5000:5000"
    volumes: 
    - "D:\\coding\\python-flask\\u_passwords\\api:/app"
    environment: 
      - ENV_FILE_LOCATION=secret.env
    links: 
      - db

  db:
    build: ./db
    volumes: 
    - ".\\db:/app/backup"
